Playwright
c4dt/d-voting pull request #79
Opened 2024-01-11 14:06 UTC by PascalinDe

This PR adds tests for the form list, including:

* checking pagination
* that forms titles are links to the forms
* the vote/results buttons are displayed correctly

it does *not* for the moment contain internalization tests, which will be added later

closes #70

2024-01-16 15:38 UTC, ineiti requested changes
Just some minor requests.

2024-01-17 12:06 UTC, PascalinDe commented on web/frontend/tests/formIndex.spec.ts
> +  const user = sciper === SCIPER_USER ? User : sciper === SCIPER_ADMIN ? Admin : undefined;
I agree on the readability, but sadly this breaks the linting

2024-01-17 12:10 UTC, PascalinDe commented on web/frontend/tests/formIndex.spec.ts
> +  const user = sciper === SCIPER_USER ? User : sciper === SCIPER_ADMIN ? Admin : undefined;
added a commit w/ linting on that line disabled, so we can either use that or leave it like before

2024-01-18 09:04 UTC, ineiti approved these changes

2024-01-18 09:35 UTC, merged